export const s = {
    app: { minHeight: "100vh", display: "flex", flexDirection: "column" },
    bannerWrap: { padding: "12px 20px" },
    nav: {
      display: "flex",
      gap: 4,
      padding: "12px 20px",
      background: "rgba(0,0,0,0.3)",
      borderBottom: "1px solid rgba(255,255,255,0.06)",
    },
    tab: {
      padding: "8px 16px",
      background: "transparent",
      border: "none",
      color: "var(--text-muted)",
      borderRadius: 6,
      cursor: "pointer",
    },
    tabActive: { background: "var(--accent-dim)", color: "var(--accent)" },
    main: {
      flex: 1,
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 24,
      padding: 24,
      overflow: "auto",
    },
    left: { minWidth: 0 },
    right: { minWidth: 0 },
    diagram: {
      display: "flex",
      alignItems: "center",
      gap: 24,
      padding: 40,
    },
    box: {
      padding: 24,
      background: "var(--card)",
      borderRadius: 12,
      border: "1px solid rgba(255,255,255,0.08)",
    },
    boxTitle: { fontWeight: 600, marginBottom: 8 },
    boxDesc: { color: "var(--text-muted)", fontSize: 14 },
    arrow: { fontSize: 24, color: "var(--accent)" },
    card: {
      padding: 24,
      background: "var(--card)",
      borderRadius: 8,
      border: "1px solid rgba(255,255,255,0.05)",
    },
    toggleBtn: {
      marginRight: 8,
      marginTop: 8,
      padding: "8px 16px",
      background: "var(--accent-dim)",
      border: "none",
      borderRadius: 6,
      color: "var(--accent)",
      cursor: "pointer",
    },
    eventLog: {
      marginTop: 16,
      padding: 12,
      background: "var(--card)",
      borderRadius: 6,
      fontSize: 13,
      color: "var(--accent)",
      border: "1px solid rgba(255,160,0,0.2)",
    },
    statusBar: {
      display: "flex",
      gap: 24,
      padding: "8px 20px",
      background: "rgba(0,0,0,0.3)",
      borderTop: "1px solid rgba(255,255,255,0.06)",
      fontSize: 12,
      color: "var(--text-muted)",
    },
  };
  